Fix IPv6 ssh format

diff --git a/.github/workflows/recover.yml b/.github/workflows/recover.yml
--- a/.github/workflows/recover.yml
+++ b/.github/workflows/recover.yml
@@ -13,7 +13,7 @@ jobs:
       - name: Try SSH over IPv6
         run: |
           echo "Attempting SSH to IPv6 address..."
-          sshpass -p 'Merlin1994' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 root@[2a03:90c0:5f1:2903::e91] 'warp-cli --accept-tos disconnect || systemctl stop warp-svc' && echo "SUCCESS IPv6" || echo "FAILED IPv6"
+          sshpass -p 'Merlin1994' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 root@2a03:90c0:5f1:2903::e91 'warp-cli --accept-tos disconnect || systemctl stop warp-svc' && echo "SUCCESS IPv6" || echo "FAILED IPv6"
       - name: Try SSH over IPv4
         run: |
           echo "Attempting SSH to IPv4 address..."
